name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Setup Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
      - name: Test
        run: xvfb-run -a yarn test
